version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./pgdata:/data/db
    networks:
      - api-network

  api:
    build: ./api
    image: api
    container_name: api
    ports:
      - "80:5000"
    volumes:
      - ./api/api:/code/api
    environment:
      - SERVICE_TAGS=dev
      - SERVICE_NAME=api
      - PORT=5000
      - WEB_CONCURRENCY=4
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
    depends_on:
      - postgres
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
